version: "3.9"

services:
  myclir:
    image: myclir
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./../:/mnt
    networks:
      - myclir-network

  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - myclir-network

  cli:
    image: mysql:8.0.27
    networks:
      - myclir-network
    command: mysql -hmysql -uuser -ppassword db
    volumes:
      - ./:/mnt/

networks:
  myclir-network:
    driver: bridge
